import TableOfContents from "../text/TableOfContents";
import ContentLevelOne from "../text/ContentLevelOne";
import Body from "../text/Body";
import Section from "../text/Section";
import SubSection from "../text/SubSection";
import SubSubSection from "../text/SubSubSection";
import References from "../text/References";
import BulletItem from "../text/BulletItem";
import SubBulletItem from "../text/SubBulletItem";
import SubSubBulletItem from "../text/SubSubBulletItem";
import Hyperlink from "../text/Hyperlink";
import Italics from "../text/Italics";
import LabeledItem from "../text/LabeledItem";
import ReferenceItem from "../text/ReferenceItem";
import ArticleImage from "../text/ArticleImage";

export default function EverydayWebUsage() {
    return (
        <>
            <TableOfContents> 
                <ContentLevelOne text="Statement From The Authors"/>
                <ContentLevelOne text="Why Are Security And Privacy Important?"/>
                <ContentLevelOne text="Passwords: Do You Use Passwords For One Or More Of Your Online Accounts?"/>
                <ContentLevelOne text="Online Finances: Do You Shop, Manage Your Bank, Or Pay Rent Online?"/>
                <ContentLevelOne text="Social Media: Do You Use Any Social Media Apps?"/>
                <ContentLevelOne text="Appendix"/>
            </TableOfContents> 
            <Section>Statement From The Authors</Section>
            <Body>This collection of advice is an academic project written by Northwestern University students for the course CS 396/496 (Winter 2023): Security & Privacy Education. The authors have not received any sponsorship from any organization or institution for this project. All the websites and applications mentioned or recommended in our advice have provided free personal versions at the time the advice was constructed.</Body>
            <Section>Passwords: Do You Use Passwords For One Or More Of Your Online Accounts?</Section>
            <Italics>One day, as John Doe is setting his password for his Facebook account, he remembers Bob—a friend of his who once told him that he should test the strength of his passwords—and decides to give it a try.
            He goes to a testing website and tests the 8 character password he came up with. It turns out that the password can be cracked in 0 seconds.</Italics>
            <Italics>Then he tests a combination of his parents' birth years, the first letters of his and his parents' names, three symbols, and his birthday, and it turns out that the password would take 17 centuries to crack. He's quite satisfied with the result, but curious how secure it can get. John tests a password generated by a password generator and finds that it would likely take 9 hundred trillion years to crack.</Italics>
            <SubSection>Setting Strong Passwords</SubSection>
            <SubSubSection>Create Strong Passwords</SubSubSection>
            <BulletItem>Make sure your password is complex enough (length & variety in types)</BulletItem>
            <BulletItem>Don't use commonly used words or consecutive numbers</BulletItem>
            <BulletItem>Don't use well-known phrases, quotes, or song lyrics</BulletItem>
            <BulletItem>Don't use easy-to-find personal information like your birthday</BulletItem>
            <SubSubSection>Check Your Password with <Hyperlink href="https://www.passwordmonster.com/" text="Password Strength Meter"/></SubSubSection>
            <BulletItem>Check your password with an password strength meter</BulletItem>
            <SubSubSection>Use A Password Generator And Password Manager</SubSubSection>
            <BulletItem>Use a <Hyperlink href="https://passwordsgenerator.net/" text="password generator"/> and password manager like <Hyperlink href="https://bitwarden.com/products/personal" text="Bitwadern"/></BulletItem>
            <BulletItem>Use Chrome with Google's built-in password generator & manager</BulletItem>
            <SubBulletItem>When you register, click the password text box.</SubBulletItem>
            <SubSubBulletItem>If you don't find that option, right-click the password text box, and then click Generate password.</SubSubBulletItem>
            <SubBulletItem>Click 'Use suggested password'.</SubBulletItem>
            <SubBulletItem>Your generated password is automatically saved to your Google Account.</SubBulletItem>
            <SubBulletItem>Next time you try to login, your browser will automatically fill the password for you.</SubBulletItem>
            <SubBulletItem>Check the <Hyperlink href="https://support.google.com/chrome/answer/95606?hl=en&co=GENIE.Platform%3DDesktop#zippy=" text="Google Password Manager Site"/> for details.</SubBulletItem>
            <SubSection>Use Unique Passwords For Essential Accounts</SubSection>
            <Italics>Several days later, John is browsing the internet when he finds an interesting start-up website providing a 15% OFF coupon for signing up.
            He decides to reuse the password he created for his bank account.
            Later, a hacker easily hacks the database of the start-up website and gets John's username and password.</Italics>
            <Italics>Because John reused his bank account password, the hacker was able to log in to John's bank account and stole all his money.</Italics>
            <BulletItem>Use unique passwords for all the essential accounts in the Essential Account Checklist.</BulletItem>
            <SubSection>Use Two Factor Authentication (2FA)</SubSection>
            <Italics>One day, Bob—John's cybersecurity expert friend—advises John to enable a new technique, Two Factor Authentication, to further protect his security.
            Two Factor Authentication, or 2FA, is an extra login security function that requires you to authenticate yourself with another device. In practice, when John needs to login to his account on his computer, he also needs to approve it from an app on his phone.</Italics>
            <Italics>After John starts using Two Factor Authentication, a hacker was able to get John's username and password.</Italics>
            <Italics>However, because John had enabled 2FA, the hacker was NOT able to steal John's money this time, as he could not authenticate himself.</Italics>
            <SubSubSection>What Is Two Factor Authentication?</SubSubSection>
            <BulletItem>An extra login security function that requires you to authenticate yourself by using another device, or through biometrics.</BulletItem>
            <BulletItem>The most effective way to protect your privacy.</BulletItem>
            <BulletItem>Use proper settings to make the process less time consuming and painful.</BulletItem>
            <BulletItem>According to Microsoft Security, 2FA can block 99.9% of account compromise attacks.</BulletItem>
            <SubSubSection>What Might It Look Like To Implement 2 Factor Authentication?</SubSubSection>
            
                <ArticleImage src="https://guide.duo.com/static/images/en/universal-enrollment-choose_2x.png"  style={{ width: '300px', height: 'auto' }}/>
            
            <Hyperlink href="https://guide.duo.com/universal-prompt?wvideo=d6kzpc5ojl" text="Video from DUO—A Popular Two Factor Authentication App" />
            
                <ArticleImage src="https://embed-ssl.wistia.com/deliveries/526c02cd75cde05326fa327e5b700a7ab9214ec9.jpg"  style={{ width: '600px', height: 'auto' }}/>
            
            <SubSection>Expire Your Passwords Periodically</SubSection>
            <Italics>One day, John received an email from his company about the auto-expiration of his work account. He thought his company would make better security decisions than him. So he decided to change passwords for his other important account once his working account's password expires. This great practice is suggested by a lot of security experts.</Italics>
            <Body>Take advantage of notifications for enforced auto-expired accounts and expire all the passwords for essential accounts in the Essential Account Checklist all at once.</Body>
            <SubSection>Be Aware Of Shoulder Surfing</SubSection>
            <Italics>One day, when John is working in a coffee shop, he enters his password for his online shopping account. Meanwhile, a stranger looked over his shoulder and memorized his username and password.</Italics>
            <BulletItem>Be aware of shoulder surfing, especially in public places</BulletItem>
            <SubBulletItem>Libraries, coffee shops, shopping malls, etc.</SubBulletItem>
            <SubBulletItem>Especially when you need to enter your password, or look at confidential data</SubBulletItem>
            <BulletItem>Never store your password in unencrypted files like notebooks</BulletItem>
            <SubSection>Take Action When Password Disclosure Happens</SubSection>
            <BulletItem>It's NOT your fault!</BulletItem>
            <BulletItem>Change the password immediately</BulletItem>
            <SubBulletItem>Avoid using similar passwords as the disclosed one(s)</SubBulletItem>
            <SubBulletItem>Change the related password, especially for essential accounts</SubBulletItem>
            <BulletItem>Contact professionals if anything (suspicious transfers, odd emails) has already happened</BulletItem>
            <Section>Online Finances</Section> 
            <SubSubSection>Do You Shop, Manage Your Bank, Or Pay Rent Online?</SubSubSection>
            <SubSection>Stay Updated</SubSection>
            <Body>Always use updated operating systems and web browsers [3][8]. By staying updated, your technology will have fewer bugs and vulnerabilities than old, outdated versions.</Body>
            <Body>Some popular operating systems are Windows or macOS on your computer and iOS or Android on your phone. Some popular browsers are Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, and Internet Explorer. Your operating system and browser depend on which device you own and how it's set up.</Body>
            <Body>To update your operating system, you'll need to go on your device itself. Here's an example using Windows 10:</Body>
            
                <ArticleImage src="https://i.ibb.co/jWm81np/updateos1.png" />
            
            <Italics>In your device's search bar, search for “Updates". Click on the result, “Check for updates", or Updates & Security, or a similar phrase.</Italics>
            
                <ArticleImage src="https://i.ibb.co/c6ht0F0/updateos2.png" />
            
            <Italics>Your device will tell you if your operating system is up-to-date, or if there are new updates to be installed.</Italics>
            <SubSection>Check For HTTPS, Not HTTP</SubSection>
            <Body>The S stands for Secure! When a website is HTTPS instead of HTTP, your payment info is extra secure. To check for HTTPS, it's as easy as looking at the URL box at the top of your web browser.</Body>
            
                <ArticleImage src="https://i.ibb.co/0ZXnyZw/https1.png" />
            
            
                <ArticleImage src="https://i.ibb.co/FDH8byd/https2.png" />
            
            <Italics>Google Chrome: In the first Image, the lock means the website is secure. But, stay on guard! HTTPS doesn't guarantee the website is 100% scam free.
            In the second Image, the URL box says “Not secure". CAUTION! Beware! Definitely do NOT give this website your payment info!</Italics>
            
                <ArticleImage src="https://i.ibb.co/kJwfrF3/https3.png" />
            
            
                <ArticleImage src="https://i.ibb.co/dGRhbPK/https4.png" />
            
            <Italics>Microsoft Edge: In the first Image, the lock is showing, AND the start of the URL says HTTPS.</Italics>
            <Italics>In the second Image, there is no lock and it says “Not secure" instead. Stay away!</Italics>
            <SubSection>Use Built-In Enhanced Security Protection</SubSection>
            <Body>Many modern browsers, like Google Chrome, have some enhanced security protection built-in. Enhanced security protection automatically protects against dangerous websites and downloads. Most modern web browsers have this feature. Here's how you enable it in Google Chrome:</Body>
            
                <ArticleImage src="https://i.ibb.co/M8zvGSK/enhanced1.png" />
            
            <Italics>Click the three dots at the top right corner of the browser, and then select Settings.</Italics>
            
                <ArticleImage src="https://i.ibb.co/Vq0TmLx/enhanced2.png" />
            
            <Italics>In settings, click Privacy and security on the left side, and then select Security.</Italics>
            
                <ArticleImage src="https://i.ibb.co/VDtFqP8/enhanced3.png" />
            
            <Italics>Click the option box for “Enhanced protection". Your web browsing will now be more protected!</Italics>
            <SubSection>Be Aware Of Your Environment</SubSection>
            <Body>Only use your own personal device for online banking and payments since public devices are less secure. If you must use a public device, use an incognito window and don't store any information. Most modern browsers have some form of incognito window. Here's how to open one on Google Chrome:</Body>
            
                <ArticleImage src="https://i.ibb.co/st8bP5L/incognito1.png"  style={{ width: '400px', height: 'auto' }}/>
            
            <Italics>Click the three dots at the top right corner of the browser, and then select New Incognito window.</Italics>
            
                <ArticleImage src="https://i.ibb.co/4YtzprH/incognito3.png" />
            
            <Italics>A new dark-colored window will pop up. Use this window to browse the web! Once you close this window, your information, like your passwords, will automatically be deleted.</Italics>
            <SubSection>Monitor Your Online Security Status</SubSection>
            <Body>Know when things go wrong! It's always easier to fix problems if you catch them right away.</Body>
            
                <ArticleImage src="https://i.ibb.co/4fHn1fL/monaccsec.png"  style={{ width: '550px', height: 'auto' }}/>
            
            <Italics>First, a hacker obtains Bob's bank account info.</Italics>
            <Italics>Next, since Bob had security alerts on, he was able to see the fishy transfer and contact his bank ASAP.</Italics>
            <Italics>However, if Bob hadn't had security alerts on, a week would've passed, and Bob's money would have been gone forever.</Italics>
            <Italics>Since Bob had alerts on, though, he defended himself against the attack!</Italics>
            <SubSection>Check For Previous Data Breaches</SubSection>
            <Body>Check if your information has been involved in previous data breaches. If one of your passwords was compromised before, check up on EVERY account that used that password and change it!</Body>
            <Body>You can check if you've been compromised at <Hyperlink href="https://haveibeenpwned.com/" text="haveibeenpwned"/>.</Body>
            
                <ArticleImage src="https://i.ibb.co/9bTQ6c8/haveibeenpwned.png"  style={{ width: '550px', height: 'auto' }}/>
            
            <Italics>On haveibeenpwned.com, just enter your email or mobile number into the search bar. Scroll down, and it'll tell you which breaches affected you.</Italics>
            <SubSection>Set Up Account Alerts</SubSection>
            <Body>Nearly 42 million Americans were victims of identity fraud in 2021, costing consumers $52 billion in total losses. </Body>
            <Body>You can monitor for identity theft by setting up account alerts. Here is how to set up alerts for Bank of America—the process will be similar for other banks.</Body>
            
                <ArticleImage src="https://i.ibb.co/34ZpjTj/accalerts1.png"  style={{ width: '550px', height: 'auto' }}/>
            
            <Italics>On the dashboard, click on Alerts, and then click on Set up alerts. On other banking sites, just look for any button that says Alerts, or use the search bar.</Italics>
            
                <ArticleImage src="https://i.ibb.co/SNV0NPg/accalerts2.png"  style={{ width: '550px', height: 'auto' }}/>
            
            <Italics>On the Set up alerts page, select General & Security alerts from the left side.</Italics>
            
                <ArticleImage src="https://i.ibb.co/XjjVPkn/accalerts3.png"  style={{ width: '550px', height: 'auto' }}/>
            
            <Italics>In General & Security alerts, you can enable any alerts that might notify you about security attacks.</Italics>
            <Section>Social Media: Do You Use Any Social Media Apps?</Section>
            <SubSection>Common Types of Social Media Scams</SubSection>
            <Body>Some common types of social media scams are phishing scams, lottery prize scams, investment scams, charity scams, job scams, and romance scams.</Body>
                <BulletItem> <strong>Phishing scams</strong> are scams where scammers use fake profiles or websites to trick users into providing sensitive information.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/aWXBnbw.jpg"  style={{ width: '500px', height: 'auto' }}/>

                <BulletItem><strong>Lottery prize scams</strong> are scams where scammers claim the user has won a prize, and ask for a payment before they can claim their winnings.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/nZbaZvJ.jpg"  style={{ width: '500px', height: 'auto' }}/>

                <BulletItem><strong>Investment scams</strong> are scams where scammers promise a high return on investment, but actually steal the user’s money.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/tX1PXhT.gif"  style={{ width: '450px', height: 'auto' }}/>

                <BulletItem> <strong>Charity scams</strong> are scams where scammers pose as a legitimate charity organization and ask for donations, but they actually use the money for their own purposes.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/s9YyxjS.jpg"  style={{ width: '500px', height: 'auto' }}/>

                <BulletItem> <strong>Job scams</strong> are scams where scammers offer fake job opportunities, ask for a fee to process the application, and steal personal information.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/uPmC3Ch.jpg"  style={{ width: '500px', height: 'auto' }}/>

                <BulletItem> <strong>Romance scams</strong> are scams where scammers pretend to be interested in a romantic relationship but actually use the relationship to scam the victim.</BulletItem>
                
                    <ArticleImage src="https://i.imgur.com/xjwWeNe.jpg"  style={{ width: '500px', height: 'auto' }}/>

            <SubSection>Tips To Avoid Falling For A Social Media Scammer</SubSection>
            <LabeledItem label="1">Be skeptical</LabeledItem>
            <SubBulletItem>Be cautious and question messages or offers that come from unknown or unverified sources.</SubBulletItem>
            <SubBulletItem>Verify the authenticity of the person and the offer before responding.</SubBulletItem>
            <SubBulletItem>Don't provide any information until you have verified the identity of the sender.</SubBulletItem>
            <LabeledItem label="2">Verify authenticity</LabeledItem>
            <SubBulletItem>Look out for the blue check mark for verified social media accounts.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/t09Z2eU.png"  style={{ width: '700px', height: 'auto' }}/>
                
            <SubBulletItem>Check the number of followers; famous people and organizations have a lot of followers.</SubBulletItem>
            <SubBulletItem>Verify authenticity of profiles, websites, and organizations.</SubBulletItem>
            <SubBulletItem>Charity navigator (below) helps you identify valid charity organizations.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/F2CVAjA.jpg" />
                
            <SubBulletItem>Visit official websites of organizations and contact them through a verified phone number.</SubBulletItem>
            <LabeledItem label="3">Keep software up-to-date</LabeledItem>
            <SubBulletItem>Regularly update the operating system. For Mac users: click on the Apple menu in the top-left corner of your screen, select "System Preferences", click on “Software Update."</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/AaYB1U4.png" />
                
            <SubBulletItem>Keep your browser up-to-date. Click the top-right “update" button (shown below) on your Google Chrome browser.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/xFh15Kd.png" />
                
            <SubBulletItem>Install anti-virus software and keep it up-to-date.</SubBulletItem>
            <SubBulletItem>Enable two-factor authentication.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/EeYkXeI.png" />
                
            (Screenshot above shows two-factor authentication on Instagram: Instagram, Profile, Edit profile, Privacy & Security)
            <LabeledItem label="4">Be mindful of privacy settings</LabeledItem>
            <SubBulletItem>Regularly review privacy settings.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/nQACwfu.png" />
                
            <Body>To get to the screen above on a Mac: (click on the Apple menu in the top-left corner of your screen, Select "System Preferences", Click on Security & Privacy), then you can check and adjust your privacy settings</Body>
            <SubBulletItem>Avoid sharing personal information on social media.</SubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/i4jE81Z.png" />
                
            <Body>What's wrong with the post above? Mariam is sharing her physical address, her medical condition, and her whereabouts on Saturday mornings. Please don't share these on social media. Also, don't share your SSN number, financial information, or passwords.</Body>
            <SubSubBulletItem>Avoid clicking on suspicious links.</SubSubBulletItem>
                
                    <ArticleImage src="https://i.imgur.com/ZdtltCm.png" />
                
            <Section>Appendix</Section>
            <SubSection>Essential Account Checklist</SubSection>
            <BulletItem>Bank account</BulletItem>
            <BulletItem>Office automation account (e.g. work or school account)</BulletItem>
            <BulletItem>Online shopping account (e.g. Amazon)</BulletItem>
            <BulletItem>Email account (especially important, as it's commonly used to authenticate all other accounts)</BulletItem>
            <BulletItem>Any other account that matters to you</BulletItem>
            <SubSection>Organizations And Individuals To Contact</SubSection>
            <BulletItem>Friends and family who have a cybersecurity background</BulletItem>
            <BulletItem>Corresponding businesses such as:</BulletItem>
            <SubBulletItem>Your Bank</SubBulletItem>
            <SubBulletItem>Any website's customer service</SubBulletItem>
            <SubBulletItem>Any other customer service or “Contact Us" page on any website, such as those of government orgs like the FTC</SubBulletItem>
            <References>
                <ReferenceItem label="1">https://bettermoneyhabits.bankofamerica.com/en/privacy-security/how-to-create-a-strong-password</ReferenceItem>
                <ReferenceItem label="2">https://www.usenix.org/conference/soups2022/presentation/lee</ReferenceItem>
                <ReferenceItem label="3">https://www.usenix.org/system/files/conference/soups2015/soups15-paper-ion.pdf</ReferenceItem>
                <ReferenceItem label="4">https://www.usenix.org/conference/soups2021/presentation/gerlitz</ReferenceItem>
                <ReferenceItem label="5">https://arxiv.org/pdf/1805.06542.pdf</ReferenceItem>
                <ReferenceItem label="6">https://www.usenix.org/publications/loginonline/how-do-people-change-their-passwords-after-breach</ReferenceItem>
                <ReferenceItem label="7">https://www.youtube.com/watch?v=rbhyfFygagA</ReferenceItem>
                <ReferenceItem label="8">https://www.bankofamerica.com/information/supported-browsers/</ReferenceItem>
                <ReferenceItem label="9">https://www.bankofamerica.com/security-center/overview/tip-sheets-smishing.pdf</ReferenceItem>
                <ReferenceItem label="10">https://securityadvice.cs.umd.edu/index.html</ReferenceItem>
                <ReferenceItem label="11">https://support.google.com/chrome/answer/7570435?hl=en&co=GENIE.Platform%3DDesktop</ReferenceItem>
                <ReferenceItem label="12">https://www.ftc.gov/news-events/data-visualizations/explore-data</ReferenceItem>
                <ReferenceItem label="13">https://www.microsoft.com/en-us/security/blog/2019/08/20/one-simple-action-you-can-take-to-prevent-99-9-percent-of-account-attacks/</ReferenceItem>
                <ReferenceItem label="14">https://www.aarp.org/money/scams-fraud/info-2020/ftc-fraud-complaints-rise.html</ReferenceItem>
                <ReferenceItem label="15">https://www.aarp.org/money/scams-fraud/info-2019/fake-celebrity.html</ReferenceItem>
                <ReferenceItem label="16">https://www.techtarget.com/searchsecurity/definition/two-factor-authentication</ReferenceItem>
                <ReferenceItem label="17">https://javelinstrategy.com/2022-Identity-fraud-scams-report</ReferenceItem>
                <ReferenceItem label="18">https://guide.duo.com/universal-prompt?wvideo=d6kzpc5ojl</ReferenceItem>
            </References>
        </>
    )
}